config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "reviews#index"
  get 'reviews/search'
  
  resources :users, only: [:show, :edit, :update, :delete]
  resources :songs, only: [:show, :index] do
    resources :reviews, only: [:index, :new, :create]
  end
  resources :reviews, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :song
  
  with_options presence: true do
    validates :review_text, length: { maximum: 280 }
    validates :rate,numericality: {
      less_than_or_equal_to: 5,
      greater_than_or_equal_to: 1}
  end
end

app/models/song.rb
class Song < ApplicationRecord
  has_many :reviews

  with_options presence: true do
    validates :song_name
    validates :song_image
    validates :song_url
    validates :song_composer
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reviews
  has_one_attached :image_name
  with_options presence: true do
    validates :email
    validates :password,format: { with: /(?=.*[a-zA-Z])(?=.*\d)[a-zA-Z\d]{6,}/, message: "は、半角英数字混合での入力が必須" },on: :create
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_search

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :password, :password_confirmation ])
    devise_parameter_sanitizer.permit(:account_update, keys: [:nickname])
  end

  def set_search
    @q = Song.ransack(params[:q])
    @result = @q.result(distinct: true).page(params[:page])
  end
  def after_sign_out_path_for(resource)
    root_path
   end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, only: [ :new, :create ]

  def index
    @reviews = Review.all.limit(5).order("id DESC")
    @songs = Song.all.limit(4).order("id DESC")
  end

  def new
    @song = Song.find(params[:song_id])
    @review = Review.new
  end

  def create
    if Review.create(review_params)
      redirect_to root_path
    else
      render :new
    end
  end

  def search
  end
  def destroy
    Review.find(params[:id]).destroy
    redirect_to root_path
  end

  private
  def review_params
    params.require(:review).permit(:review_title, :review_text, :rate).merge(user_id: current_user.id, song_id: params[:song_id])
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show]

  def index
    @songs = Song.all.order("id DESC")
  end
  def show
    @reviews = @song.reviews.order("id DESC").page(params[:page]).per(5)
    @songs = Song.order("RAND()").limit(3)
  end

  private
  def set_song
    @song = Song.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [ :edit ]
  before_action :set_user, only: [:edit, :show, :update]
  before_action :move_to_edit, only: [:edit, :update]

  def show
    @reviews = @user.reviews.order("id DESC").page(params[:page]).per(5)
    @email = @user.email
  end

  def new
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  
  private
  def user_params
    params.require(:user).permit(:nickname, :image_name)
  end

  def move_to_edit
    unless current_user.id == @user.id
      redirect_to root_path
    end
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vocaview</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- コード追加　Bootstrap CSS読み込みコード-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!-- コード追加　Bootstrap JavaScript読み込みコード-->
  </head>

  <body>
  <div class=”container”>
    <%= yield %>
  <div>
  </body>
  <footer>
    <div class="footer-links__inner">
      <div class="footer-links__block">
        <ul class="footer-links__items">
          <li class="footer-links__item">
            <a href="/" class="footer-links__link">トップページへ</a>
            <a href="/reviews/search" class="footer-links__link">全ての楽曲を見る</a>
          </li>
        </ul>
      </div>
      <div class="footer-links__block">
        <ul class="footer-links__items">
          <li class="footer-links__item">
            <%=link_to "話題の楽曲一覧", songs_path, class:"footer-links__link" %>
            <a href="/" class="footer-links__link">最新のレビュー</a>
          </li>
        </ul>
      </div>
      <div class="footer-links__block">
        <ul class="footer-links__items">
          <li class="footer-links__item">
            <a href="/" class="footer-links__link">新しい楽曲一覧</a>
            <a href="/" class="footer-links__link">人気の楽曲一覧</a>
          </li>
        </ul>
      </div>
      <div class="footer-links__block">
        <ul class="footer-links__items">
          <li class="footer-links__item">
            <a href="https://forms.gle/SPnaezU8MvBuSuU16" class="footer-links__link">お問い合わせ</a>
          </li>
        </ul>
      </div>
    </div>
    <div class="footer-copyright">
      <p>
        Copyright Voccaview 2021.
      </p>
    </div>
  </footer>
</html>

app/views/reviews/index.html.erb
<%= render "shared/header" %>

<div class="photo_top">
    <%= link_to (image_tag 'header.png', class:"header-photo"), root_path %>
</div>
<div class="row-p-top-content">
  <div class="p-top-content__inner">
    <h2 class="c-heading-1">
      Vocaviewで今注目の動画
    </h2>
    <div class="row-p-top-content__trends">
    <% if @songs.blank? %>

    <% else %>
      <% @songs.each do |song| %>
      <div class="c-content-item">
        <%= link_to (image_tag song.song_image , class:"img-size_review-index-top"), song_path(song.id) %>
        <div class="top_review_item">
          <%= link_to "レビュー", new_song_review_path(song.id) ,class:"review-visit" %>
        </div>
      </div>
      <% end %>
    <% end %>
    </div>
    <div class="c-more-read">
      <%=link_to "もっと見る", songs_path, class:"c-more-read-item" %>
    </div>
 </div>
</div>
<div class="row-content_review-index">
  <h2 class="c-heading-2">
    新着レビュー
  </h2>
  <div class="p-top-content__review">
  <% if @reviews.blank? %>
  
  <% else %>
    <% @reviews.each do |review| %>
      <div class="r-content-item">
        <div class="r-content-item-top">
          <div class="content-song">
            <div class="review-song">
              <%= link_to (image_tag review.song.song_image , class:"img-size_review-index"), song_path(review.song.id)  %>
            </div>
          </div>
          <div class="review-item">
            <%= link_to "レビュー", new_song_review_path(review.song.id) ,class:"review-visit" %>
          </div>
        </div>
        <div class="r-content-item-under">
          <div class="review-right">
            <div class="rigth-top">
              <div class="review-usericon">
                <% if review.user.image_name.attached? %>
                  <%= image_tag review.user.image_name %>
                <% end %>
              </div>
              <div class="review-username">
              <%= link_to review.user.nickname, user_path(review.user.id) %>
              </div>
              <div class="review-star">
                <div id="star-rate-<%= review.id %>"></div>
              </div>
              <script>
                $('#star-rate-<%= review.id %>').raty({
                  size: 5,
                  starOff:  '<%= asset_path('star-off.png') %>',
                  starOn : '<%= asset_path('star-on.png') %>',
                  half: true,
                  readOnly: true,
                  score: <%= review.rate %>,
                });
              </script> 
            </div>
          </div>
          <div class="review-content">
            <div class="review-index_title">
            <%if review.review_title.blank? %>
            <%= "タイトルなし" %>
            <% else %>
            <%= review.review_title %>
            <% end %>
            </div>
            <div class="review-text">
              <%= review.review_text %>
            </div>
            <% if current_user == review.user %>
            <%= link_to (image_tag 'delete.png', class: "delete_img"), review_path(review.id), method: :delete %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
  </div>
</div>

app/views/reviews/new.html.erb
<%= render "shared/header" %>

<div class = "content-top">
  <div class = "form-area">
    <%= form_with model: [@song, @review], local: true, class: "review-form"  do |f| %>
      <div class="content-title">
        <%= @song.song_name %><%= "へのレビュー" %>
      </div>
      <div class = "input-area">
          <div class="star-area" id="star">
            <%= f.label :star,'評価 ', class:'col-md-3 col-form-label' %>
            <%= f.hidden_field :star, id: :review_star %>
          </div>

          <!-- 評価javascript -->
         <script>
         $('#star').raty({
           size     : 50,
           starOff:  '<%= asset_path('star-off.png') %>',
           starOn : '<%= asset_path('star-on.png') %>',
       
           scoreName: 'review[rate]',
           half: false,
         });
         </script> 

        <div class="review-title">
          <%= f.text_field :review_title, class: "input-title", placeholder: "タイトル"  %>
        </div>
        <div class="review-area">
          <%= f.text_area :review_text, class: "input-review", size: "40x10" %>
        </div>
        <div class="submit-form">
          <%= f.submit "投稿する", class: "form-sub" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/reviews/search.html.erb
<%= render "shared/header" %>

<div class="search_song_content">
    <h2 class="search_song_content_title">
    <%= "検索結果"%>
    </h2>
  <div class="search_song_content_under">
    <% @result.each do |f| %>
    <div class="search_song_item">
      <div class="search_song_song">
        <%= link_to (image_tag f.song_image , class:"img-size_review-search-top"), song_path(f.id) %>
      </div>
      <div class="search_song_name">
        <%= link_to f.song_name, song_path(f.id) %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header>
  <div class = "high_header">
  <% if user_signed_in? %>
   <ul class="login_list">
     <li><%= link_to current_user.nickname, user_path(current_user.id), class: "login_item"  %></li>
     <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "login_item" %></li>
   </ul>
  <% else %>
   <ul class="login_list">
     <li><%= link_to "会員登録",  new_user_registration_path, class:"login_item" %></li>
     <li><%= link_to "ログイン",  new_user_session_path, class:"login_item" %></li>
   </ul>
  <% end %>
  </div>
</header>
<div class="search">
  <%= link_to (image_tag 'icon.png',class:"icon_img"), root_path, class:"icon" ,size:"320x240" %>
  <%= search_form_for @q, url: reviews_search_path do |f| %>
    <%= f.search_field :song_name_or_song_composer_cont, class: "search_box", placeholder: "キーワードを入力(例: 曲名 )" %>
    <%= f.submit "検索", class: "btn btn-default" %>
  <% end %>
</div>

app/views/songs/index.html.erb
<%= render "shared/header" %>

<div class="search_song_content">
    <h2 class="search_song_content_title">
    <%= "今話題の楽曲"%>
    </h2>
  <div class="search_song_content_under">
    <% @songs.each do |f| %>
    <div class="search_song_item">
      <div class="search_song_song">
      <%= link_to (image_tag f.song_image , class:"img-size_review-search-top"), song_path(f.id) %>
      </div>
      <div class="search_song_name">
      <%= link_to f.song_name, song_path(f.id) %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/songs/show.html.erb
<%= render "shared/header" %>

<div class="content-container"> <!--画面全体-->
  <div class="content-main"><!--歌情報部分-->
    <div class="song_show_content">
      <h1 class="song-title">
        <%= @song.song_name %>
        <div class="song_review-item">
          <%= link_to "この曲のレビューを書く", new_song_review_path(@song.id) ,class:"review-visit" %>
        </div>
      </h1>
      <div class="song-img-content-top">
        <div class="song-img-content">
          <%= link_to (image_tag @song.song_image , class:"img-size_song-show"), song_path(@song.id)  %>
        </div>
        <div class="song-composer-content">
          <div class="song-composer-content_title">作曲者</div>
          <%= @song.song_composer%>
          <div class="play_video">
            <%= link_to (image_tag '764.png',class:"play_img"), "https://www.youtube.com/watch?v=#{@song.song_url}" %>
            <div class="play_video_content">
              <%= "Youtubeで再生する" %>
            </div>
          </div>
        </div>
      </div>
      <div class="song-random-content_title">
      <%= "おすすめ動画" %>
      </div>
      <div class="song-random-content-top">
        <% @songs.each do |f|%>
        <div class="song-random-content">
          <%= link_to (image_tag f.song_image , class:"img-size_random-show" ), song_path(f.id)  %>
          <%= f.song_name %>
        </div>
        <% end %>
      </div>
    </div>
    <div class="mypage-under">
      <h1 class="mypage-under_title">
        <%= @song.song_name %><%= "に投稿されたレビュー"%>
      </h1>
      <% @reviews.each do |review| %>
      <div class="r-content-item">
        <div class="r-content-item-top">
          <div class="content-song">
            <div class="review-song">
              <%= link_to (image_tag @song.song_image , class:"img-size_review-index", size:"200x150"), song_path(@song.id)  %>
            </div>
          </div>
          <div class="review-item">
            <%= link_to "レビュー", new_song_review_path(review.song.id) ,class:"review-visit" %>
          </div>
        </div>
        <div class="r-content-item-under">
          <div class="review-right">
            <div class="rigth-top">
              <div class="review-usericon">
                <% if review.user.image_name.attached? %>
                  <%= image_tag review.user.image_name %>
                <% end %>
              </div>
              <div class="review-username">
              <%= link_to review.user.nickname, user_path(review.user.id) %>
              </div>
              <div class="review-star">
                <div id="star-rate-<%= review.id %>"></div>
              </div>
              <script>
                $('#star-rate-<%= review.id %>').raty({
                  size: 50,
                  starOff:  '<%= asset_path('star-off.png') %>',
                  starOn : '<%= asset_path('star-on.png') %>',
                  half: true,
                  readOnly: true,
                  score: <%= review.rate %>,
                });
              </script> 
            </div>
          </div>
          <div class="review-content">
            <div class="review-text">
            <%= review.review_text %>
            </div>
            <% if current_user == review.user %>
            <%= link_to (image_tag 'delete.png', class: "delete_img"), review_path(review.id), method: :delete %>
            <% end %>
          </div>
        </div>
      </div>
      <% end %>
    </div>
    <%= paginate @reviews %>
  </div>
</div>

app/views/users/edit.html.erb
<%= render "shared/header" %>

<div class="edit-page">
  <div class="edit-content">
    <div class="edit_page-top">
      <div class="user_icon">
        <% if @user.image_name.attached? %>
          <%= image_tag @user.image_name.variant(resize: '80x80'), class: 'icon-image' %>
        <% end %>
      </div>
      <div class="user_nickname">
        ユーザー名 / <%= @user.nickname %>
      </div>
      <div class="user_email">
        email / <%= @user.email %>
      </div>
    </div>
    <div class="edit_page-under">
      <%= form_with model: @user, local: true, class: "edit-form"  do |f| %>
        <div class="input_name-form">
          <%= f.text_field :nickname, class: "input-name" %>
        </div>
        <div class="image-form">
          <%= f.label :プロフィール画像 %><br>
          <%= f.file_field :image_name%>
        </div>
        <div class="submit-form">
          <%= f.submit "変更する", class: "form-sub" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<%= render "shared/header" %>

<div class="mypage-content">
  <div class="mypage-top">
    <div class="user_icon">
      <% if @user.image_name.attached? %>
        <%= image_tag @user.image_name %>
      <% end %>
    </div>
    <div class="user_email">
    <%= @user.nickname %>
    </div>
    <% if current_user == @user %>
      <div class="edit-user">
        <%= link_to "プロフィール編集", edit_user_path, class:"edit-page" %>
      </div>
    <% end %>
  </div>
  <div class="mypage-under_user_show">
    <div class="mypage-under_content_user_show">
      <% @reviews.each do |review| %>
      <div class="r-content-item">
        <div class="r-content-item-top">
          <div class="content-song">
            <div class="review-song">
              <%= link_to (image_tag review.song.song_image , class:"img-size_review-index"), song_path(review.song.id)  %>
            </div>
          </div>
          <div class="review-item">
            <%= link_to "レビュー", new_song_review_path(review.song.id) ,class:"review-visit" %>
          </div>
        </div>
        <div class="r-content-item-under">
          <div class="review-right">
            <div class="rigth-top">
              <div class="review-usericon">
                <% if @user.image_name.attached? %>
                  <%= image_tag @user.image_name, class: 'icon-image' %>
                <% end %>
              </div>
              <div class="review-username">
              <%= review.user.nickname %>
              </div>
              <div class="review-star">
                <div id="star-rate-<%= review.id %>"></div>
              </div>
              <script>
                $('#star-rate-<%= review.id %>').raty({
                  size: 50,
                  starOff:  '<%= asset_path('star-off.png') %>',
                  starOn : '<%= asset_path('star-on.png') %>',
                  half: true,
                  readOnly: true,
                  score: <%= review.rate %>,
                });
              </script> 
            </div>
          </div>
          <div class="review-content">
            <div class="review-text">
            <%= review.review_text %>
            </div>
            <% if current_user == review.user %>
            <%= link_to (image_tag 'delete.png', class: "delete_img"), review_path(review.id), method: :delete %>
            <% end %>
          </div>
        </div>
      </div>
      <% end %>
      <%= paginate @reviews %>
    </div>
  </div>
</div>

app/views/users/update.html.erb
<h1>変更が完了しました。</h1>
<%= link_to "トップページへ", root_path %>